packages:
  - 'packages/*'

catalog:
  vite: ^6.0.3
  vitest: ^2.1.8
  astro: ^5.0.5
  "@astrojs/react": ^4.1.0 
  "@astrojs/mdx": ^4.0.2
  "@vitejs/plugin-react": ^4.3.4
  react: ^18.3.1
  "@types/react": ^18.3.1
  "@types/react-dom": ^18.3.1
  react-dom: ^18.3.1
  vite-plugin-dts: ^4.3.0
  typescript: ^5.7.2
  electron: ^31.0.0
  jsdom: ^24.0.0
  "eslint": "^9.17.0"
  "eslint-plugin-react": "^7.37.3"
  "@eslint/js": "^9.17.0"
  "typescript-eslint": "^8.19.0"
  "vite-plugin-eslint": "^1.8.1"
  "@types/chrome": "^0.0.287"
