packages:
  - 'packages/*'

catalog:
  vite: ^5.3.3
  vitest: ^2.0.0
  astro: ^4.16.16
  "@astrojs/react": ^3.6.3 
  "@vitejs/plugin-react": ^4.3.4
  react: ^18.3.1
  "@types/react": ^18.3.1
  "@types/react-dom": ^18.3.1
  react-dom: ^18.3.1
  vite-plugin-dts: ^4.0.2
  typescript: ^5.5.0
  electron: ^31.0.0
  jsdom: ^24.0.0
